# Generated by Django 4.2.3 on 2023-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Japan_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Japan_foods_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Japan_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thumbnail', models.ImageField(blank=True, upload_to='post', verbose_name='썸네일 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='post', verbose_name='사진')),
            ],
        ),
        migrations.CreateModel(
            name='USA_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USA_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='USA_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USA_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USA_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
            ],
        ),
    ]
