# Generated by Django 4.2.3 on 2023-08-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vietnam_others_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 잡화 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='vietnam_others_comment',
            name='vietnam_others_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.vietnam_others', verbose_name='베트남 잡화 시세 댓글'),
        ),
        migrations.AddField(
            model_name='vietnam_clothes_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 의류 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='vietnam_clothes_comment',
            name='vietnam_clothes_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.vietnam_clothes', verbose_name='베트남 의류 시세 댓글'),
        ),
        migrations.AddField(
            model_name='usa_others_comment',
            name='usa_others_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_others', verbose_name='미국 잡화 시세 댓글'),
        ),
        migrations.AddField(
            model_name='usa_others_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 잡화 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='usa_clothes_comment',
            name='usa_clothes_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='미국 의류 시세 댓글'),
        ),
        migrations.AddField(
            model_name='usa_clothes_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 의류 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.post', verbose_name='포스트'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='savior.hashtag', verbose_name='해시태그 목록'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='japan_others_comment',
            name='japan_others_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_others', verbose_name='일본 잡화 시세 댓글'),
        ),
        migrations.AddField(
            model_name='japan_others_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 잡화 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='japan_foods_comment',
            name='japan_foods_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_foods', verbose_name='일본 음식 시세 댓글'),
        ),
        migrations.AddField(
            model_name='japan_foods_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 음식 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='japan_clothes_comment',
            name='japan_clothes_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_clothes', verbose_name='일본 의류 시세 댓글'),
        ),
        migrations.AddField(
            model_name='japan_clothes_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 의류 시세 댓글 작성자'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.post', verbose_name='포스트'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
