# Generated by Django 4.2.3 on 2023-08-17 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savior', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='japan_clothes_comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
