# Generated by Django 4.2.3 on 2023-08-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savior', '0005_scrappedcountry_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ScrappedCountry',
        ),
    ]
