# Generated by Django 4.2.3 on 2023-08-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savior', '0006_delete_profile_delete_scrappedcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Japan_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('japan_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_clothes', verbose_name='일본 의류 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 의류 시세 댓글 작성자')),
            ],
        ),
    ]
