# Generated by Django 4.2.3 on 2023-08-12 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savior', '0007_japan_clothes_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Japan_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('japan_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_others', verbose_name='일본 잡화 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 잡화 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_foods_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('japan_foods_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_foods', verbose_name='일본 음식 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 음식 시세 댓글 작성자')),
            ],
        ),
    ]
