# Generated by Django 4.2.3 on 2023-08-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savior', '0008_japan_others_comment_japan_foods_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vietnam_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 잡화 시세 댓글 작성자')),
                ('vietnam_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='베트남 잡화 시세 댓글')),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 의류 시세 댓글 작성자')),
                ('vietnam_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='베트남 의류 시세 댓글')),
            ],
        ),
        migrations.CreateModel(
            name='USA_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('usa_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='미국 잡화 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 잡화 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='USA_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('usa_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='미국 의류 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 의류 시세 댓글 작성자')),
            ],
        ),
    ]
