# Generated by Django 4.2.3 on 2023-08-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savior', '0010_alter_usa_others_comment_usa_others_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vietnam_clothes_comment',
            name='vietnam_clothes_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.vietnam_clothes', verbose_name='베트남 의류 시세 댓글'),
        ),
    ]
